### ISSUE TITLE
Class yedincisenol\DynamicLinks\DynamicLink not found

### ISSUE THREAD

**Issue by adamulator** [yedincisenol/dynamic-links#5]
Hello,
I'm using Laravel 5.4. I followed instructions, but am unable to use this package because of an error 'Class '(...)\yedincisenol\DynamicLinks\DynamicLink' not found' that occurs when I try to create a link using provided sample code. I added 'yedincisenol\DynamicLinks\LaravelServiceProvider::class' to providers in `config/app.php` and `use yedincisenol\DynamicLinks\Info\Analytics\GooglePlayAnalytics;
use yedincisenol\DynamicLinks\Info\Analytics\ItunesConnectAnalytics;
use yedincisenol\DynamicLinks\Info\AnalyticsInfo;
use yedincisenol\DynamicLinks\DynamicLink;
use yedincisenol\DynamicLinks\Info\AndroidInfo;
use yedincisenol\DynamicLinks\Info\SocialMetaTag;
use yedincisenol\DynamicLinks\Info\IosInfo;` on top of my class, however error persists. What can I do about it?

**Comment by nishanth662** [comment]
Add this to your controller

use yedincisenol\DynamicLinks\DynamicLink;
use yedincisenol\DynamicLinks\DynamicLinks;

**Comment by Tarhex** [comment]
Didn't work in my case.

This worked though `$link = new \yedincisenol\DynamicLinks\DynamicLink('http://yeni.co/');`
