### ISSUE TITLE
New Guzzle Version

### ISSUE THREAD

**Issue by sirgrimorum** [yedincisenol/dynamic-links#9]
Hi,

I'm using Laravel 7, and need to add a new package that requires guzzlehttp/guzzle ^7.0, but it conflicts with yedincisenol/dynamic-links requirements (^6.3).

Any chance to update the requirements?

**Comment by yedincisenol** [comment]
@sirgrimorum I have planned this dependency update for few days

**Comment by sirgrimorum** [comment]
> @sirgrimorum I have planned this dependency update for few days

It will be most welcome

**Comment by yedincisenol** [comment]
@sirgrimorum New version `v2.0.0` released with this dependency update 👍
